name: Ping Supabase

on:
  schedule:
    # Ex√©cute toutes les 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request
        env:
          SUPABASE_URL: ${{ env.SUPABASE_URL }}
          SUPABASE_KEY: ${{ env.SUPABASE_KEY }}
        run: |
          curl -X GET "$SUPABASE_URL" -H "apikey: $SUPABASE_KEY"
